


server:
  port: 8080

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        #  AUTH SERVICE
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1

        # AUTH OAUTH ROUTES
        - id: auth-oauth
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/oauth2/**,/login/**,/error

        # QUANTITY SERVICE
        - id: quantity-service
          uri: lb://QUANTITY-SERVICE
          predicates:
            - Path=/api/quantity/**
          filters:
            - StripPrefix=1

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "${FRONTEND_URL:http://localhost:5173}"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials Access-Control-Allow-Headers Access-Control-Allow-Methods, RETAIN_UNIQUE

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}


  instance:
      prefer-ip-address: true

jwt:
  secret: ${JWT_SECRET}