spring.application.name=quantitymeasurement

# Web Server Port
server.port=8080

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:quantitydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate / JPA Settings
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Enable the H2 Console (so you can view your database in the browser)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console