# ================= SERVER =================
spring.config.import=optional:file:.env[.properties]
server.port=${PORT:8081}
spring.application.name=AUTH-SERVICE
server.forward-headers-strategy=framework

# ================= DATABASE =================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ================= JPA =================
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.sql.init.mode=always

# ================= JWT =================
jwt.secret=${JWT_SECRET}
jwt.expirationMs=86400000

# ================= EUREKA =================
eureka.client.service-url.defaultZone=${EUREKA_URL}

# ================= GOOGLE OAUTH =================
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.redirect-uri=${GOOGLE_REDIRECT_URI}

# ================= FRONTEND =================
app.frontend.redirect-url=${FRONTEND_URL}

# ================= SWAGGER =================
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

eureka.instance.prefer-ip-address=true